### ISSUE TITLE
Monitor: Cosmetic - Remove url from Grafana and AlertManager

### ISSUE THREAD

**Issue by skdwriting** [opensds/opensds-dashboard#130]
1) Can we change 
Grafana-Url --> Grafana
Alertmgr-Url --> Alert Manager

2) Can we give one line description to each of these to mention what it will provide to user?

**Comment by anvithks** [comment]
@skdwriting This is information is being received from the API and can be changed from there. Although this can be done in dashboard via code but since the API is designed specifically to populate this page we can make the necessary changes in the config file. I will talk to @NajmudheenCT and work on this.

**Comment by NajmudheenCT** [comment]
Hi @skdwriting @anvithks 
Is this response looks good 
[
   {
       "name": "Grafana",
       "url": "http://192.168.43.163:3000",
       "description": "Open Grafana tool to visualize collected metrics"
   },
   {
       "name": "Alert Manager",
       "url": "http://192.168.43.163:9093",
       "description": "Open Alert Manager to view and handle alerts sent by prometheus"
   }
]

I will be raising a PR for this

**Comment by anvithks** [comment]
@NajmudheenCT @skdwriting Reinstalling from latest and verifying this. Will inform once done.

**Comment by anvithks** [comment]
@NajmudheenCT @skdwriting This is fixed. No change required from dashboard.

![telemetry-urls](https://user-images.githubusercontent.com/19162717/59716151-0d8f6700-9233-11e9-89c3-74eda1214ec0.png)
Closing the issue.
