### ISSUE TITLE
The windows appeared to shake when creating access for share

### ISSUE THREAD

**Issue by wisererik** [opensds/opensds-dashboard#80]
**Is this a BUG REPORT or FEATURE REQUEST?**:

>
> /kind bug

**What happened**:

When I was creating an access for file share, the windows appeared to shake.

**What you expected to happen**:

The window looks normal.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Dashboard(release/branch) version: development
- OS (e.g. from /etc/os-release): ubuntu16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by anvithks** [comment]
@skdwriting Can be taken up later.

**Comment by jimccfun** [comment]
@wisererik @skdwriting @anvithks
file:///C:/Users/yWX487141/AppData/Roaming/eSpace_Desktop/UserData/ywx487141/imagefiles/C2C1E2C9-2954-4A76-89DD-D56B87894E4F.png
file:///C:/Users/yWX487141/AppData/Roaming/eSpace_Desktop/UserData/ywx487141/imagefiles/A1F867EB-22D4-4D3D-8FF9-ADAC4E9524B1.png
this reason for the windows appeared to shake is because the value of top changes between this two values.I'm trying to fix this.

**Comment by jimccfun** [comment]
@wisererik @skdwriting @anvithks 
![SUNABUIF OBX$XF(){}EA3V](https://user-images.githubusercontent.com/37950702/59907326-6b8f9a80-943d-11e9-8f27-824cb0c639a3.png)
![A8$8G8WVZX94Y7~FM8 OW0W](https://user-images.githubusercontent.com/37950702/59907339-71857b80-943d-11e9-9beb-0adf6baaca7b.png)
The reason for the windows appeared to shake is because the value of top changes between this two values, I'm trying to fix this.
