### ISSUE TITLE
Dashboard-LifeCycle: Not able to add Lifecycle rule in Edit LifeCycleConfig

### ISSUE THREAD

**Issue by satya-gorli** [opensds/opensds-dashboard#89]
1. create LifeCycle Config
2. Click Edit of the config
3. Trying to add new rule into the config
4. Add Rule is disabled in dashboard
![LifcycleIssues_EditNotAlloingToAddLifecycle rule](https://user-images.githubusercontent.com/48289385/59179329-4d918280-8b7f-11e9-92a8-358c916a8069.PNG)

**Comment by anvithks** [comment]
@jimccfun Please take a look.

**Comment by skdwriting** [comment]
Is it dup of #94 . Please check

**Comment by jimccfun** [comment]
@satya-gorli @anvithks  in Edit page if the selected storage class is GLACIER, we can no longer add new Rule. because we can only transition from STANDARD to STANDARD_IA or GLACIER, or form STANDARD_IA to GLACIER. However we can't transition in reverse. but we can switch the GLACIER to another storage class, then add new Rule. So I'm modifying this problem that supports switching from GLACIER to another storage class. so that we can add new Rule.
